sudo: required
language: ruby
cache: bundler
script:
- bundle install
- rm -rf dashboard.tgz
- tar -czf dashboard.tgz ./assets ./dashboards ./jobs ./public ./widgets ./config.ru
  ./Gemfile* ./dashing.service
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in deploy.key.enc -out deploy.key -d
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
    secure: MGIZl1tAt0BPkxgfD3gpGxH5C3rCQVLx2rYcZC9EY2O+05oX6xK42pcQkhE69KcUhCiAkqHOEVqKN4f1UzcSzpu96gGbSPh7ImdSg+h2GpdCcLgML451W1asZ7gwOQwBH4hwMD0nnZ+Z/z44cOKDmXI/CWb2vYud2Qi7fnUi36ie7HjRlpex7WQFCU1tJLznzibIsulL24BFIZKOKXt1ZorJnHnFvzu0GWRKtLBk91/61o3pPTk6KfGwdVWfjw64GB/Md2T7xKHnhr3LvMw5KMbZainNJS23aoTw5Jvh+kma3PdaqCcWKsm3ISptaeiU3dIeDQZa3cOMT5+r4he+VRF5zOkBSqrpw8HMSGiz1b7yKIBzh4z/YORZyBDncGr0i5/YpxlIk2Y9l800mnVlc2/1iLWBZDK8HmS5xKa0/qqhcGiauYOgYnMTy7MHEjs+g8+u5x+1XIGJW/kSL8QdJpp0XBLLbDmPlZ9PjuuR9PBJdyaGGDQCvdJI4rmZskXIj0s2w9mu0JYV6BJxi1qYF3DvhFBk+Np/pUjjqfPX1piDUv9EZ4pf/jhFcmzELqqXNh+5p9bT8pvf73IhUOxvPMrjHm3dc9+vmRJYKn2YNgLV437U3xgY7NnTL63MVddQID9STBFwk+nNp28h0VvsIxhGV3R4NfElkX5FIFtKVVY=
notifications:
  slack:
    secure: o/1K+YYD0RVMA/xtclATjH1PSW+cbHlS7x/VZX8WZ6nmvIza3rEeTmTp3NGdtHnxb8WPsv1irY/Zk32kePaPxklq/7QWTojADGla7hE1gprSZ5GgShIAX28n+zlHAw9nXclVkpRZN0CMPhcGeC6gg8C+lZ5eC+/tiZkuUyAEPZyybec99NbAByXKj1+5xeZRjkfXDu4g7ZFUXPvdVBBIIv0bwVXtF1hWyJIAkV67cuUaaxPM8iSZxNmF3o3VKjvvhw2fLUDOiVl0G31Igez21XOzAGS0jHWRqs/nx+Xozo4rhTP2AW5NOOqXHSp/qTP5zAeaak/HNgpFRJ80FTmsGeuLOFtoY0ZnZlec9Iyf3fnnVHQQQyf0OZwAbjGHiYRfqnEvyyD4r4EGL+vHAmyHQAgCmtYZ766uXGCILii6khlTatiFJSZsPbarSmgkSaDUrKYtK2chT28jKB7ZOdRDjHO4fLkge7aY89m34AyIxULpOTyG+8ZR9a3spm1zxK4UL5+9Uwjltqq2peqBV8MUeX9pZedpbJa3LVgawGZdXufISnsMCRbaHnfz6QKDR/SgpCM877bDXu2/ftAyRlkQumxyARlwfsFfnlEYAi7dJmg9YflS1RIPZGSCdNziPm+xlP6JppHGBpnwz6dSj+AlDzWhumSWewq5nAIzsl7brv8=
