sudo: required
language: ruby
cache: bundler
script:
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
    secure: "OCzW678FUYBmZ2tFBUHugERqU06cPQR6J2bIgkmQARMyeKgVcuwNfJoPmXED500n+x6DDCeqnA4RSfeHJJg9KzUicKCToBV/97NNjsurlaMJdlO6zsrYCcnacPF2ayTyuX933od5mT/zYmcNAfqD6cc42v2U/w1SZVYzDyBQfWMGARU5MI0ROP6Vhr6xSDge0KbNoyhq0kdBfTFRyP2Oi8QOtnYGM+CnycTrTqBU8oznWNf89xBrlIVoz31FR7vMlT8Yx3YKgzzuJ7o5k38XiQLPVLY+xULIuQR8hOXKZmO7GCORqWwQ1q3GSc43aRBbaexTm7rreLYtyDMFKDpH+YPccpnrV7MkDnMF3eh8eJqiOI+QmMAyG//yiWygW8TwrprU+bUUcUxIH1tScVQgmvULDzM752ramrBCL+E7HhpsYYpNnUYkFVqHp9Hlt7fjWcwnS0j3M6P3uP2InWMR2/jX1CnXFqFbglym+TgxkDt+u6b7TgCqxIqzEYqAiANIQy66HbCqr3NeqUqASTvOrnCOWlnsYWuACUePAVBBpThaYfCa88CW44yy228TxkVqKhbOQD8qvmpZTHgc0IknoFLHqnVX4/MgNYAPb9fgKyLQre3S4KXvBehe0gB9KqPoJPtVJTGzX42+jsXkBUR5uFNw0JLQcPecWEyEMRPEg7U="
notifications:
  slack:
    secure: o/1K+YYD0RVMA/xtclATjH1PSW+cbHlS7x/VZX8WZ6nmvIza3rEeTmTp3NGdtHnxb8WPsv1irY/Zk32kePaPxklq/7QWTojADGla7hE1gprSZ5GgShIAX28n+zlHAw9nXclVkpRZN0CMPhcGeC6gg8C+lZ5eC+/tiZkuUyAEPZyybec99NbAByXKj1+5xeZRjkfXDu4g7ZFUXPvdVBBIIv0bwVXtF1hWyJIAkV67cuUaaxPM8iSZxNmF3o3VKjvvhw2fLUDOiVl0G31Igez21XOzAGS0jHWRqs/nx+Xozo4rhTP2AW5NOOqXHSp/qTP5zAeaak/HNgpFRJ80FTmsGeuLOFtoY0ZnZlec9Iyf3fnnVHQQQyf0OZwAbjGHiYRfqnEvyyD4r4EGL+vHAmyHQAgCmtYZ766uXGCILii6khlTatiFJSZsPbarSmgkSaDUrKYtK2chT28jKB7ZOdRDjHO4fLkge7aY89m34AyIxULpOTyG+8ZR9a3spm1zxK4UL5+9Uwjltqq2peqBV8MUeX9pZedpbJa3LVgawGZdXufISnsMCRbaHnfz6QKDR/SgpCM877bDXu2/ftAyRlkQumxyARlwfsFfnlEYAi7dJmg9YflS1RIPZGSCdNziPm+xlP6JppHGBpnwz6dSj+AlDzWhumSWewq5nAIzsl7brv8=
