sudo: required
language: ruby
cache: bundler
script:
  - bundle install
  - rm -rf dashboard.tgz
  - tar -czf dashboard.tgz ./assets ./dashboards ./jobs ./public ./widgets ./config.ru ./Gemfile* ./dashing.service
before_install:
  - openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv -in deploy.key.enc -out deploy.key -d
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
    secure: "gQ+xP2MAlsLYjMPFh4IMitEoH/SmwruH8hzeQQq3ZSo0hkE8oRZyYJH7Ud3s3gkbP7MMgqwQdxxPMO3nrZoUrMWa/19duDQU81XZsCVl/hqSlMaaJ1H4YGGQdPqdnFBTmznanUwQ6yvvU3G2LRpX/WIluP32mi1kvvkYBBzqbSMhLV8iNHBYZ31oxJA+ryTJloD2dyaje0LRypIMhrG27JSkvgwEC/OKa0Cv8ilisMNA0AEv1XAbwIvd8nljw9SaaXHIOUwqsyCl0l2fLLDydQjoMjUPGz69FcyHfjOb96pvtuMbkBXGnOiFCyNLMfG1C9VNcx/7VeCbqjIf5laX6YyfNHUbfke25Gm/rk3GTjvkvWhlcJvRgY7IKGbfiUhtniVX7PPb5p4HkCnztkpys0wLY9OEzXii6tGOo/HDxluw8wQod149STbjDEiiaMrVu514AeK7NK+RD8sY3iYs/M/5EY1XJbJDqHIK/v05mOBCy9Bw6A+icbkK8lChKV9h/a0KtBimRNRPM9CKhflvbCJUxG6pAywaHrJtcXl6lWQC3FJWmERVVIPOB4Uty+xIpEfLowVqrZe1dvgWS5Kpph/CzNAaBPzwexI0pw+1BtkLsnkwmiQ6WUPpDkVscYggQMj0DVL24+anAdmW+BMCELYkQWMAHks7qi9lC5PcR8s="
notifications:
  slack:
    secure: o/1K+YYD0RVMA/xtclATjH1PSW+cbHlS7x/VZX8WZ6nmvIza3rEeTmTp3NGdtHnxb8WPsv1irY/Zk32kePaPxklq/7QWTojADGla7hE1gprSZ5GgShIAX28n+zlHAw9nXclVkpRZN0CMPhcGeC6gg8C+lZ5eC+/tiZkuUyAEPZyybec99NbAByXKj1+5xeZRjkfXDu4g7ZFUXPvdVBBIIv0bwVXtF1hWyJIAkV67cuUaaxPM8iSZxNmF3o3VKjvvhw2fLUDOiVl0G31Igez21XOzAGS0jHWRqs/nx+Xozo4rhTP2AW5NOOqXHSp/qTP5zAeaak/HNgpFRJ80FTmsGeuLOFtoY0ZnZlec9Iyf3fnnVHQQQyf0OZwAbjGHiYRfqnEvyyD4r4EGL+vHAmyHQAgCmtYZ766uXGCILii6khlTatiFJSZsPbarSmgkSaDUrKYtK2chT28jKB7ZOdRDjHO4fLkge7aY89m34AyIxULpOTyG+8ZR9a3spm1zxK4UL5+9Uwjltqq2peqBV8MUeX9pZedpbJa3LVgawGZdXufISnsMCRbaHnfz6QKDR/SgpCM877bDXu2/ftAyRlkQumxyARlwfsFfnlEYAi7dJmg9YflS1RIPZGSCdNziPm+xlP6JppHGBpnwz6dSj+AlDzWhumSWewq5nAIzsl7brv8=
