sudo: required

language: ruby

cache: bundler

script:
  - bundle install

before_install:
  - openssl aes-256-cbc -K $encrypted_424929f292a8_key -iv $encrypted_424929f292a8_iv -in deploy.key.enc -out deploy.key -d

deploy:
  skip_cleanup: true
  provider: script
  script: deploy.sh
  on:
    branch: master
