sudo: required
language: ruby
cache: bundler
script:
  - set -e
  - bundle install
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
env:
  global:
    secure: "CVb7IGC5tOGhIcYZMl3jw8pSzgCXknjTH0T+/PdzaDQpuHrvrbP1Puc7Bn4UwP04LJQ/hKsf5yjuQCwZYETXfKz8U2yV0ETYihT/KrNyiu55YFl3Cc4gSuhski9WfyLQRSN7wIWoUH99PZRZ4p77ez7vLZ1EiJySp3iglEk18ZtNpOLwIkwNSfG15lWYu/GrL0SJlr4xoj3OkF/fQwPlFyXDr/YDgl2BercFjhi69sGiUQhJ8U4KxLfksnVafWv0TM9xoJYcBq+idxot05Ex4yVlXyzeXlIXJVRi51kRJSAv9VeYVBj6xJF5UW6alKlYGYpcMVyumWDSk1k7PATnoU6jPdmBsrGN99yRgsATOjINkIuXhRm9IfIkrRZeMpC3FQt8UX9XdnKxy2vbX20TZ6mVln4AxJV2pcyZquJw++VHzWsCqNArAhL7IiQMzNUFJufE2NV1RhEeYLtcUwhzGuu0k7w2df6/Izy0hnNe6egWJwCImEfWz9qWLG6e9XwMQdw8CAzUaU4jJjhPTS02DObS4xifsljaStNkzCrrt8TbtbabiuYiSVgXK8MoL015IKoTfkKq4FBg0KwmaYJeKuFNT3OoPBG0el76UYJ86jiQVEhxEPWzd42Z2+1twhXKimfrkAeCmb1CoKNLspq2zyLEFp1rUFtprKFaVNTPMCo="
notifications:
  slack:
    secure: o/1K+YYD0RVMA/xtclATjH1PSW+cbHlS7x/VZX8WZ6nmvIza3rEeTmTp3NGdtHnxb8WPsv1irY/Zk32kePaPxklq/7QWTojADGla7hE1gprSZ5GgShIAX28n+zlHAw9nXclVkpRZN0CMPhcGeC6gg8C+lZ5eC+/tiZkuUyAEPZyybec99NbAByXKj1+5xeZRjkfXDu4g7ZFUXPvdVBBIIv0bwVXtF1hWyJIAkV67cuUaaxPM8iSZxNmF3o3VKjvvhw2fLUDOiVl0G31Igez21XOzAGS0jHWRqs/nx+Xozo4rhTP2AW5NOOqXHSp/qTP5zAeaak/HNgpFRJ80FTmsGeuLOFtoY0ZnZlec9Iyf3fnnVHQQQyf0OZwAbjGHiYRfqnEvyyD4r4EGL+vHAmyHQAgCmtYZ766uXGCILii6khlTatiFJSZsPbarSmgkSaDUrKYtK2chT28jKB7ZOdRDjHO4fLkge7aY89m34AyIxULpOTyG+8ZR9a3spm1zxK4UL5+9Uwjltqq2peqBV8MUeX9pZedpbJa3LVgawGZdXufISnsMCRbaHnfz6QKDR/SgpCM877bDXu2/ftAyRlkQumxyARlwfsFfnlEYAi7dJmg9YflS1RIPZGSCdNziPm+xlP6JppHGBpnwz6dSj+AlDzWhumSWewq5nAIzsl7brv8=
